name: iOS Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_ios:
    name: Build iOS
    runs-on: macos-14
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # latest stable
        
    - name: Flutter version check
      run: |
        flutter --version
        dart --version
        
    - name: Install dependencies
      run: |
        # Retry a few times in case of transient network issues
        for i in 1 2 3; do
          flutter pub get --verbose && break || {
            echo "pub get failed (attempt $i), retrying in 10s...";
            sleep 10;
          }
        done
      
    - name: CocoaPods repo update (iOS)
      run: |
        pod --version
        pod repo update

    - name: Build iOS (unsigned)
      run: |
        flutter build ios --release --no-codesign --verbose
      
    - name: Create IPA
      run: |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r ../../../FotoJeolog.ipa Payload/
        ls -la ../../../FotoJeolog.ipa
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: FotoJeolog-iOS
        path: FotoJeolog.ipa
        retention-days: 7