name: iOS Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_ios:
    name: Build iOS
    runs-on: macos-13
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
        
    - name: Flutter version check
      run: flutter --version
        
    - name: Install dependencies
      run: |
        flutter pub get --verbose
      
    - name: Build iOS (unsigned)
      run: |
        flutter build ios --release --no-codesign --verbose
      
    - name: Create IPA
      run: |
        cd build/ios/iphoneos
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r ../../../FotoJeolog.ipa Payload/
        ls -la ../../../FotoJeolog.ipa
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: FotoJeolog-iOS
        path: FotoJeolog.ipa
        retention-days: 7