name: iOS TestFlight

on:
  workflow_dispatch:

jobs:
  build_and_upload:
    name: Build & Upload TestFlight
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter doctor
        run: |
          flutter --version
          dart --version

      - name: Install dependencies
        run: |
          for i in 1 2 3; do
            flutter pub get --verbose && break || { echo "Retry pub get $i"; sleep 10; }
          done

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install fastlane
        run: |
          gem install fastlane -NV

      - name: Decode signing assets
        env:
          IOS_CERT_P12: ${{ secrets.IOS_CERT_P12 }}
          IOS_PROVISIONING_PROFILE: ${{ secrets.IOS_PROVISIONING_PROFILE }}
        run: |
          mkdir -p signing
          echo "$IOS_CERT_P12" | base64 --decode > signing/cert.p12
          echo "$IOS_PROVISIONING_PROFILE" | base64 --decode > signing/profile.mobileprovision

      - name: Keychain setup
        env:
          IOS_CERT_PASSWORD: ${{ secrets.IOS_CERT_PASSWORD }}
        run: |
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import signing/cert.p12 -k build.keychain -P "$IOS_CERT_PASSWORD" -A
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      - name: Xcode provisioning
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          # Use a deterministic name based on profile UUID
          PROFILE_UUID=$(security cms -D -i signing/profile.mobileprovision | /usr/libexec/PlistBuddy -c 'Print:UUID' /dev/stdin)
          cp signing/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$PROFILE_UUID.mobileprovision

      - name: CocoaPods repo update
        run: |
          pod repo update

      - name: Prepare bundle id & exportOptions.plist
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          IOS_BUNDLE_ID: ${{ secrets.IOS_BUNDLE_ID }}
        run: |
          # Extract data from provisioning profile
          security cms -D -i signing/profile.mobileprovision > signing/profile.plist
          PROFILE_NAME=$(/usr/libexec/PlistBuddy -c 'Print:Name' signing/profile.plist)
          APP_ID=$(/usr/libexec/PlistBuddy -c 'Print:Entitlements:application-identifier' signing/profile.plist)
          TEAM_PREFIX=$(echo "$APP_ID" | sed -E 's/\..*$//')
          BUNDLE_FROM_PROFILE=$(echo "$APP_ID" | sed -E 's/^[^.]+\.//')

          # Prefer explicit secret if provided, else use profile bundle id
          FINAL_BUNDLE_ID=${IOS_BUNDLE_ID:-$BUNDLE_FROM_PROFILE}

          # Patch project bundle identifiers to match
          sed -i '' "s/com.example.yeniClean/${FINAL_BUNDLE_ID}/g" ios/Runner.xcodeproj/project.pbxproj
          # Patch DEVELOPMENT_TEAM in project settings
          sed -i '' -E "s/DEVELOPMENT_TEAM = [A-Z0-9]+;/DEVELOPMENT_TEAM = ${APPLE_TEAM_ID};/g" ios/Runner.xcodeproj/project.pbxproj || true

          # Create dynamic exportOptions for manual signing
          cat > ios/exportOptions.dynamic.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>${APPLE_TEAM_ID}</string>
            <key>uploadSymbols</key>
            <true/>
            <key>compileBitcode</key>
            <false/>
            <key>signingStyle</key>
            <string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${FINAL_BUNDLE_ID}</key>
              <string>${PROFILE_NAME}</string>
            </dict>
          </dict>
          </plist>
          EOF

      - name: Build iOS (codesign)
        env:
          DEVELOPMENT_TEAM: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          xcodebuild -version
          SECURITY_MULTIPLEXING=1 flutter build ipa --release --export-options-plist=ios/exportOptions.dynamic.plist --verbose

      - name: Upload to TestFlight
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ secrets.ASC_KEY_ID }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.ASC_API_KEY_P8 }}
        run: |
          IPA_PATH=$(ls build/ios/ipa/*.ipa | head -n 1)
          xcrun altool --upload-app -f "$IPA_PATH" -t ios --apiKey "$APP_STORE_CONNECT_KEY_IDENTIFIER" --apiIssuer "$APP_STORE_CONNECT_ISSUER_ID" --verbose
